name: flutter_sms_example
description: Demonstrates how to use the flutter_sms plugin.
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_sms:
    path: ../
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
